### ISSUE TITLE
Support some system assets CAR files

### ISSUE THREAD

**Issue by aonez** [bartoszj/acextract#11]
Thanks for this tool @bartoszj!

Just trying some system asset files that return no result. For example those:

- `/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car`
- `/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAppearance.car`
- `/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAquaAppearance.car`

No time now but might give it a debug later.

**Comment by tristanSIF** [comment]
There's no image in these files.
By dumping info with command `xcrun assetutil --info SystemAppearance.car -o info.json`, it contains only 'Data' files


Data | ✘

**Comment by aonez** [comment]
@tristanSIF I'm getting some images too, altough they are `PSD`, maybe that is the issue:

```json
  {
    "AssetType" : "Image",
    "BitsPerComponent" : 8,
    "ColorModel" : "Monochrome",
    "Colorspace" : "srgb",
    "Compression" : "lzfse",
    "EdgeInsets" : "top:4.000 left:4.000 bottom:4.000 right:4.000",
    "Encoding" : "Gray",
    "Image Type" : "kCoreThemeNinePartScale",
    "Name" : "SquareButton.psd",
    "Opaque" : false,
    "PixelHeight" : 20,
    "PixelWidth" : 28,
    "Presentation State" : "Active",
    "RenditionName" : "SquareButton.psd",
    "Scale" : 1,
    "SHA1Digest" : "9DB3B185318818DA24BF21D09139C4D90A53E5F2",
    "SizeOnDisk" : 462,
    "State" : "Pressed",
    "Value" : "Off"
  }
```

**Comment by aonez** [comment]
I've extracted them using another tool.
